# Generated by Django 3.2.10 on 2022-05-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
