# Generated by Django 3.2.10 on 2022-05-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220509_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
