# Generated by Django 3.2.10 on 2022-05-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_question_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.CharField(blank=True, default=4, max_length=100, null=True),
        ),
    ]
